### ISSUE TITLE
Can @Loggable log exceptions at the configured log level?

### ISSUE THREAD

**Issue by jhansoty73** [jcabi/jcabi-aspects#149]
For a method annotated with `@Loggable(Loggable.DEBUG)` the method entry and exit messages use the configured log level, DEBUG in this case, but if the method throws an exception then a message gets logged at the ERROR level. 

For an exception that propagates up a call stack, this will result in multiple ERROR logs. I really want the ERROR log, if needed, be generated by the code that eventually handles the exception.

For my use case it would be ideal if the exception logging honored the log level setting in `@Loggable`. Would this **fix** be of interest?

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@jhansoty73 yes, we should fix this, thanks

**Comment by broomzhang** [comment]
Hello @yegor256 

First, thank you very much for your great work of this aspectj project, and it helped us a lot.
But I have also encountered this same log level issue, and it does impact the log heavily, so I hope this bug could be fixed.

Because I am new to aspect, I am not sure if I have found the real bug, but I hope my info could help.
It seems that at: com.jcabi.aspects.aj.MethodLogger.java line 231, 
instead of "Loggable.ERROR", the log level should be something like annotation.value()

Hope this info will help to fix this bug, and thanks again for this great work.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.2`

**Comment by yegor256** [comment]
@jhansoty73 @broomzhang I fixed it in a6d2021

**Comment by yegor256** [comment]
@jhansoty73 @broomzhang try version 0.22.2

**Comment by broomzhang** [comment]
@yegor256 Thank you very much for your lightning fast fix.
the version 0.22.2 works perfectly now.

**Comment by yegor256** [comment]
@jhansoty73 please, close this ticket. thanks!
