### ISSUE TITLE
JSR303Test.java:61-64: When I replaced our own...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#173]
Puzzle `169-0e4b9121` in `src/test/java/com/jcabi/aspects/JSR303Test.java:61-64` has to be resolved: When I replaced our own validation with that of hibernate-validator for #34, this test stopped working in openJDK6, but remained working in all the other JDKs we're using on Travis CI. This test should pass without errors.... The puzzle was created by Suseika on 9-Jul-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@yamstranger this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by YamStranger** [comment]
@dmarkov this issue will be tested?

**Comment by dmarkov** [comment]
> @dmarkov this issue will be tested? 

@yamstranger @yegor256 I guess it's a question for you or @Suseika

**Comment by Suseika** [comment]
@YamStranger What do you mean by that?

**Comment by YamStranger** [comment]
@Suseika @dmarkov  I mean, what status of this issue. Problem was, in "test should pass without errors...." it was fixed, tests are successful. What next? )

**Comment by Suseika** [comment]
@YemStranger If you remove the `@Ignore` annotation under the todo and run the build in Travis, will it succeed? The issue is that this test is failing with a particular JDK on Travis.

**Comment by YamStranger** [comment]
@Suseika I created pull request to prove it )

**Comment by YamStranger** [comment]
@dmarkov is this issue fixed?

**Comment by YamStranger** [comment]
@Suseika @dmarkov, merge merged successfully. Test complete successfully at all JDK 1.5-1.7. I think this issue already can be closed.

**Comment by Suseika** [comment]
@YamStranger In order for it to be closed, you should post a comment to the author of the issue (in this case, to dmarkov) with a link to the PR where it was solved, saying that the task is done.

**Comment by YamStranger** [comment]
@Suseika Thanks.

**Comment by YamStranger** [comment]
@dmarkov this issue was fixed under #184 .  I think this issue already can be closed.

**Comment by YamStranger** [comment]
@dmarkov ping )

**Comment by dmarkov** [comment]
> @dmarkov is this issue fixed? 
> 

@yamstranger if you removed the puzzle, I will close the ticket right after the next deployment cycle

**Comment by YamStranger** [comment]
@dmarkov deployment was successful. Would you like to close this issue? Thanks

**Comment by YamStranger** [comment]
@dmarkov It seems that issue can be closed, but I Need More Time to be sure, and may be provide some fixes. Thanks

**Comment by dmarkov** [comment]
> @dmarkov It seems that issue can be closed, but I Need More Time to be sure, and may be provide some fixes. Thanks

@yamstranger of course, take your time

**Comment by YamStranger** [comment]
@dmarkov deployment was successful. Would you like to close this issue? Thanks

**Comment by dmarkov** [comment]
> @dmarkov deployment was successful. Would you like to close this issue? Thanks

@yamstranger sure, will close soon if you removed the puzzle

**Comment by YamStranger** [comment]
@dmarkov May be I do something wrong... This pazzle was removed in  PR #183 . Am I doing something wrong?

**Comment by YamStranger** [comment]
@dmarkov I added reference to PR #183 where, as I think this pazzle closed. 
For my opinion, puzzle is:
1) Build field under java 1.6 because of replacing our own validation with that of hibernate-validator for #34 

So, I fix it in PR #183 , after that we cask about this from @Suseika , is this puzzle closed. He asked me try to build and run tests with removing "@Ignore" annotation to enable failed test case. 
For this purpose I create PR #184 and build here successfull to. 

Merged #183 and #184 prove that Build under 1.6 and other Java successful with hibernate-validator (using of it configured throws Pom file). 

@dmarkov So, I think that this puzzle resolved. It I am wrong - please explain where. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov May be I do something wrong... I think, that this pazzle was removed in  PR #183 . Am I wrong?  

@yamstranger I don't see where you removed the puzzle, in #183

**Comment by YamStranger** [comment]
@dmarkov May be my understanding of puzzle is wrong, @Suseika can you help with it?

For my opinion, puzzle is:
1) Build field under java 1.6 because of replacing our own validation with that of hibernate-validator for #34

That means, that when build will be successful with hibernate-validations and  removed @Igonore annotation from "problem test case" - puzzle will be removed.

Thanks

**Comment by Suseika** [comment]
@YamStranger There are task descriptions right in the source code that are called "puzzles", they start with `@todo`. 

If you're working on a task that was created by such puzzle (like this task was), then you should remove the puzzle from source code when you're done working on it. You didn't do that, and code reviewer missed that too in #183. That's why @dmarkov won't close the issue.

You should create another pull request that will remove the `@todo` from source code, then after it is merged write to @dmarkov that the issue is done in that pull request (not in #183).

**Comment by Suseika** [comment]
@YamStranger The location of the puzzle in source code can be found in the top post of an issue generted by such puzzle:

> Puzzle 169-0e4b9121 in src/test/java/com/jcabi/aspects/JSR303Test.java:61-64

**Comment by YamStranger** [comment]
@Suseika you are great!!! Thanks a lot

**Comment by dmarkov** [comment]
> @dmarkov May be my understanding of puzzle is wrong, @Suseika can you help with it?
> 
> For my opinion, puzzle is:
> 1) Build field under java 1.6 because of replacing our own validation with that of hibernate-validator for #34
> 
> That means, that when build will be successful with hibernate-validations and  removed @Igonore annotation from "problem test case" - puzzle will be removed.
> 
> Thanks
> 

@yamstranger only @Suseika can help you :)

**Comment by dmarkov** [comment]
@yegor256 Thanks all, I am closing

**Comment by dmarkov** [comment]
@yamstranger **30 mins** was added to your account, many thanks for your contribution (payment 66422876)! The task took 481 hours and 11 mins.

added +30 to your rating, now it is equal to [+15](http://www.netbout.com/b/35267?open=rating)
