### ISSUE TITLE
MethodValidator.java:194-197: It's a temporary design, which...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-aspects#34]
Puzzle `61-1692fcb2` in `src/main/java/com/jcabi/aspects/aj/MethodValidator.java:194-197` has to be resolved: It's a temporary design, which enables only NotNull, Valid, and Pattern annotations. In the future we should use JSR-303 Validator, when they implement validation of values (see their appendix C).

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by carlosmiranda** [comment]
@dmarkov I need you to assign someone else, sorry.

**Comment by dmarkov** [comment]
> @dmarkov I need you to assign someone else, sorry.

@carlosmiranda someone else will help in this task, no problem at all

**Comment by dmarkov** [comment]
@yamstranger the issue is yours, please help

**Comment by YamStranger** [comment]
@dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger 30 points was deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else. Sorry.  It seems I was in @away mode when this task was assigned. @yegor256 can you check it please? Thanks.

@yamstranger right, I'll try to find someone else for this task

**Comment by dmarkov** [comment]
@bertram25 This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by Bertram25** [comment]
@yegor256 Hi, I've made a few semi-working tries but I'm stuck in the middle ~3/4 of the road here.
Speaking of the JSR-303 API method value validation isn't enough IMHO. It doesn't tell whether we can/should? replace the main functions signatures of the MethodValidator class to fit more the standard Validator class, (which is the validator implementation of the corresponding Validator interface as far as I understood.) or whether the functions there must absolutely stay as is for backward compatibility as it is told the functions documentation, and then the Validator itself must be used otherwise.

For me, or for the next one, if you could document a bit the final desired MethodValidator API, it could help, IMHO.
Thanks in advance. :)

@dmarkov Hi, I fear won't have enough time to finish that task unfortunately due to RL stuff, so please assign somebody else. My apologies for the time taken. I also know I'll lose rating points but that's life.

Best regards,

**Comment by yegor256** [comment]
@dmarkov assign someone else pls

**Comment by dmarkov** [comment]
> @dmarkov assign someone else pls

@yegor256 30 points was deducted from your rating

**Comment by dmarkov** [comment]
> @dmarkov assign someone else pls

@yegor256 I will assign somebody else to this issue

**Comment by dmarkov** [comment]
@suseika please proceed, it's yours

**Comment by Suseika** [comment]
@dmarkov I need more time

**Comment by dmarkov** [comment]
> @dmarkov I need more time

@suseika yeah, I know, take your time

**Comment by dmarkov** [comment]
@rultor rultor closed it by mistake, @dmarkov please take a look

**Comment by Suseika** [comment]
@dmarkov Closed in #169

**Comment by dmarkov** [comment]
> @dmarkov Closed in #169 

@suseika will close it right after the next deployment cycle (if you removed the puzzle)

**Comment by dmarkov** [comment]
@yegor256 Finished, thanks, closing..

**Comment by dmarkov** [comment]
@suseika **30 mins** was added to your account, many thanks for your contribution (payment AP-6GF00171S2394381S)! The task took 382 hours and 57 mins.; added +30 to your rating, now it is equal to [+458](http://www.netbout.com/b/35381?open=rating)
